import { PhotoStyle } from './types';

export const PHOTO_STYLES: PhotoStyle[] = [
  // 1-20 Original
  { id: 1, category: "Classic", name: "法式慵懒写真", promptSuffix: "French lazy style portrait, soft natural lighting, effortless chic, romantic atmosphere" },
  { id: 2, category: "Urban", name: "都市酷感机能风", promptSuffix: "Urban techwear style, cool vibes, street fashion, neon city background, futuristic functional clothing" },
  { id: 3, category: "Sweet", name: "少女梦幻写真", promptSuffix: "Dreamy teenage style, soft pastel colors, ethereal lighting, fairytale atmosphere, sparkles" },
  { id: 4, category: "Retro", name: "复古港风胶片", promptSuffix: "Hong Kong retro film style, 90s aesthetic, cinematic grain, moody lighting, nostalgic red and green tones" },
  { id: 5, category: "Minimal", name: "高级极简风", promptSuffix: "High-end minimalist style, clean background, neutral colors, fashion magazine editorial look" },
  { id: 6, category: "Business", name: "商务气场大片", promptSuffix: "Business professional power portrait, sharp suit, confident pose, modern office or studio background" },
  { id: 7, category: "Outdoor", name: "户外大景人像", promptSuffix: "Outdoor landscape portrait, epic scenery, wide angle, natural light, harmonious composition with nature" },
  { id: 8, category: "Mood", name: "雨夜情绪写真", promptSuffix: "Rainy night mood, cinematic lighting, wet streets, reflection, umbrella, melancholic atmosphere" },
  { id: 9, category: "Sci-Fi", name: "未来赛博风", promptSuffix: "Cyberpunk futuristic style, neon lights, glitch effects, high-tech accessories, night city" },
  { id: 10, category: "Life", name: "生活纪实风", promptSuffix: "Documentary lifestyle, candid moment, authentic, messy hair, cozy home or street setting" },
  { id: 11, category: "Art", name: "暗黑艺术风", promptSuffix: "Dark art aesthetic, gothic elements, dramatic shadows, mysterious, high contrast, moody" },
  { id: 12, category: "Sweet", name: "公主系甜美写真", promptSuffix: "Princess style, sweet and elegant, tiara, ballgown elements, soft pink and white tones, castle vibe" },
  { id: 13, category: "Sport", name: "运动元气系", promptSuffix: "Energetic sports style, sportswear, gym or track background, sweat, dynamic pose, bright daylight" },
  { id: 14, category: "Nature", name: "温室花房写真", promptSuffix: "Greenhouse conservatory, surrounded by flowers and plants, soft diffused sunlight, botanical aesthetic" },
  { id: 15, category: "Travel", name: "旅行度假风", promptSuffix: "Travel vacation style, tropical or landmark background, sunglasses, summer outfit, relaxed vibe" },
  { id: 16, category: "Japanese", name: "和风日系清冷", promptSuffix: "Japanese cool tone portrait, minimal, clean, soft blue tints, serene expression, film photography look" },
  { id: 17, category: "Lighting", name: "黄昏逆光写真", promptSuffix: "Golden hour backlight, silhouette, lens flare, warm orange tones, romantic and nostalgic" },
  { id: 18, category: "Cultural", name: "中式古典人像", promptSuffix: "Traditional Chinese classical portrait, hanfu elements, oriental aesthetics, elegant, ink painting vibe" },
  { id: 19, category: "Fashion", name: "城市摩登封面风", promptSuffix: "Modern city magazine cover, vogue style, bold makeup, statement fashion, skyscrapers in background" },
  { id: 20, category: "Creative", name: "情绪室内黑光", promptSuffix: "Indoor black light photography, UV reactive makeup, glowing neon paint, dark room, artistic experimentation" },

  // 21-50 Extended
  { id: 21, category: "Summer", name: "加州阳光海滩风", promptSuffix: "California sunshine, beach vibes, bright blue sky, palm trees, warm saturation, film kodak look" },
  { id: 22, category: "Minimal", name: "北欧清冷人像", promptSuffix: "Nordic minimal cold tone, white snow or grey concrete, clean lines, desaturated colors, winter vibes" },
  { id: 23, category: "Youth", name: "校园青春系", promptSuffix: "Campus youth, school uniform or casual hoodie, library or playground, fresh face, nostalgic school days" },
  { id: 24, category: "Sport", name: "都市夜跑运动风", promptSuffix: "Urban night runner, activewear, motion blur background, city street lights, sweat, intense focus" },
  { id: 25, category: "Art", name: "复古油画感人像", promptSuffix: "Oil painting style portrait, textured brushstrokes, classical lighting, museum quality, rich colors" },
  { id: 26, category: "Creative", name: "漫画分镜风", promptSuffix: "Manga storyboarding style, black and white ink, speech bubbles, dramatic angles, comic book aesthetic" },
  { id: 27, category: "Sci-Fi", name: "科幻光束摄影", promptSuffix: "Sci-fi light beam, laser lights, geometric shadows, futuristic studio, glowing lines" },
  { id: 28, category: "Retro", name: "蒸汽波色彩系", promptSuffix: "Vaporwave aesthetic, purple and teal gradient, retro 80s computer graphics, marble statues, glitch art" },
  { id: 29, category: "Art", name: "梦境反射水面", promptSuffix: "Dream reflection, water surface ripples, surreal composition, double exposure, mirrored world" },
  { id: 30, category: "Travel", name: "荒野公路风", promptSuffix: "Road trip wanderer, desert highway, vintage car, dusty boots, americana vibe, freedom" },
  { id: 31, category: "Vintage", name: "绅士/淑女复古肖像", promptSuffix: "Vintage gentleman/lady portrait, 1920s Gatsby style, tuxedo or flapper dress, sepia tone, elegant poise" },
  { id: 32, category: "Fantasy", name: "森林精灵系", promptSuffix: "Forest fairycore, magical woods, glowing fireflies, fantasy costume, mystical atmosphere" },
  { id: 33, category: "Mood", name: "极夜蓝调人像", promptSuffix: "Blue hour arctic mood, deep blue twilight, cold atmosphere, solitude, minimal light source" },
  { id: 34, category: "Life", name: "复古胶片家居感", promptSuffix: "Retro home film, cozy interior, warm tungsten light, grainy film texture, intimate and relaxed" },
  { id: 35, category: "Abstract", name: "超现实扭曲空间", promptSuffix: "Surreal distortion, dali-esque melting background, fish-eye lens, dream logic, strange perspective" },
  { id: 36, category: "Creative", name: "霓虹舞台人像", promptSuffix: "Neon stage portrait, spotlight, stage smoke, performance vibe, vibrant colors, pop star energy" },
  { id: 37, category: "Life", name: "咖啡馆文艺系", promptSuffix: "Cafe indie mood, looking through window, coffee cup, warm cozy tones, intellectual vibe, soft focus" },
  { id: 38, category: "Summer", name: "夏日泳池光影", promptSuffix: "Poolside summer glow, shimmering water caustics, bright sunlight, blue tiles, wet hair, refreshing" },
  { id: 39, category: "Street", name: "街头涂鸦色彩系", promptSuffix: "Graffiti pop color, urban wall art background, bold streetwear, vibrant saturation, hip hop culture" },
  { id: 40, category: "Industrial", name: "工业硬核风", promptSuffix: "Industrial metal aesthetic, abandoned factory, steel structures, rusty textures, cold rough lighting" },
  { id: 41, category: "Western", name: "美式牛仔西部风", promptSuffix: "Western cowboy/cowgirl, denim and leather, horse ranch background, sunset, rugged charm" },
  { id: 42, category: "Party", name: "夜店闪光捕捉", promptSuffix: "Flash photography party, direct flash, high contrast, club background, energetic, candid snapshot" },
  { id: 43, category: "Grunge", name: "脏乱美颓废风", promptSuffix: "Messy grunge portrait, torn clothes, smudged makeup, raw texture, rebellious attitude, 90s rock" },
  { id: 44, category: "Life", name: "温柔居家光", promptSuffix: "Morning soft light indoor, bed sheets, waking up, pure white sunlight, gentle and intimate" },
  { id: 45, category: "Costume", name: "万圣节角色扮演", promptSuffix: "Halloween cosplay portrait, dramatic costume, spooky makeup, theatrical lighting, character acting" },
  { id: 46, category: "Travel", name: "海岛随拍度假风", promptSuffix: "Island casual portrait, breeze in hair, ocean background, linen clothes, effortless vacation look" },
  { id: 47, category: "Art", name: "极具色块构成", promptSuffix: "Color-block avant-garde, solid geometric background colors, high fashion pose, abstract composition" },
  { id: 48, category: "Mood", name: "暗室红光摄影", promptSuffix: "Darkroom red light, safe light aesthetic, developing photos, monochromatic red, intense mood" },
  { id: 49, category: "Sci-Fi", name: "科技反射玻璃风", promptSuffix: "Tech glass reflection, looking through glass, digital overlays, prism effects, modern office futuristic" },
  { id: 50, category: "Silhouette", name: "星空下剪影", promptSuffix: "Silhouette under the stars, milky way background, starry night, mysterious outline, cosmic scale" },

  // New Holiday Styles
  { id: 51, category: "Holiday", name: "圣诞节日写真", promptSuffix: "Christmas holiday portrait, festive red and green, bokeh lights, snow, cozy winter vibe, Santa hat optional" },
  { id: 52, category: "Holiday", name: "复活节梦幻风", promptSuffix: "Easter holiday portrait, pastel colors, spring flowers, bunny ears element, soft dreamy lighting, wonderland" },
  { id: 53, category: "Holiday", name: "亡灵节暗黑风", promptSuffix: "Day of the Dead Dia de los Muertos, sugar skull makeup art, marigold flowers, vibrant colors, dark mysterious atmosphere" },
  
  // New Chinese Cultural Styles
  { id: 54, category: "Cultural", name: "中式汉服风格", promptSuffix: "Traditional Chinese Hanfu portrait, flowing silk robes, wide sleeves, intricate embroidery, elegant hairstyle with hairpins, ancient garden background, ethereal atmosphere" },
  { id: 55, category: "Cultural", name: "中式明朝服饰", promptSuffix: "Chinese Ming Dynasty portrait, mamianqun horse face skirt, cross-collar robe, gold jewelry, dignified pose, classical Chinese architecture background, rich colors" },
  { id: 56, category: "Cultural", name: "中式清朝服饰", promptSuffix: "Chinese Qing Dynasty portrait, traditional Manchurian dress, qipao, floral headdress (dianzi), delicate embroidery, palace garden background, noble elegance" },
  { id: 57, category: "Cultural", name: "苗族服饰风格", promptSuffix: "Miao ethnic minority portrait, elaborate silver headdress and jewelry, colorful embroidered traditional clothing, festival atmosphere, vibrant patterns, cultural heritage" },
  { id: 58, category: "Cultural", name: "彝族服饰风格", promptSuffix: "Yi ethnic minority portrait, traditional black and red clothing with yellow patterns, large fringed headwear, silver ornaments, mountainous landscape background, bold and spirited" },

  // New Styles Batch 3
  { id: 59, category: "Fashion", name: "高定礼服写真", promptSuffix: "High-end couture evening gown portrait, elegant red carpet look, luxurious fabric, diamonds and jewelry, sophisticated pose, gala event atmosphere" },
  { id: 60, category: "Korean", name: "韩系清纯写真", promptSuffix: "Korean portrait style, clean 'glass skin' makeup, soft natural lighting, minimal studio background, ulzzang aesthetic, pure and innocent vibe" },
  { id: 61, category: "Fashion", name: "高冷御姐风", promptSuffix: "Mature 'cool sister' style, confident and domineering expression, sharp blazer or fashion coat, modern city luxury background, strong independent aura" },
  { id: 62, category: "Cultural", name: "中式旗袍风格", promptSuffix: "Traditional Chinese Cheongsam Qipao portrait, silk texture, Shanghai 1930s vibe, elegant curves, fan or tea prop, oriental classical beauty, cinematic lighting" },
  { id: 63, category: "Retro", name: "经典港风女神", promptSuffix: "Classic Hong Kong beauty, flowing wavy hair, red lips, soft focus hazy filter, 80s movie star aesthetic, glamorous and nostalgic" },
  { id: 64, category: "Korean", name: "韩系财阀千金", promptSuffix: "Korean chaebol daughter style, rich girl aesthetic, tweed jacket, pearl accessories, expensive interior background, elegant, haughty and sophisticated" },
  { id: 65, category: "Fashion", name: "摩登黑色系", promptSuffix: "Modern black fashion style, confident woman in stylish black outfit and sheer black tights, high heels, night city background, cool mysterious vibe, vogue photography" },
  { id: 66, category: "Sweet", name: "甜美白丝少女", promptSuffix: "Sweet girl style, white knee-high socks, cute dress, pastel colors, soft daylight, kawaii aesthetic, innocent and charming pose" },

  // New Styles Batch 4 (User Request)
  { id: 67, category: "Art", name: "法式油画风格", promptSuffix: "French oil painting style, textured brushstrokes, romantic pastel colors, soft light, vintage garden background, elegant and artistic, masterpiece" },
  { id: 68, category: "Korean", name: "纯欲风格", promptSuffix: "Pure and sultry style, soft focus, flushed cheeks, innocent yet charming expression, white lace or silk camisole, intimate indoor lighting, dreamy atmosphere" },
  { id: 69, category: "Japanese", name: "日系少女风格", promptSuffix: "Japanese fresh girl style, JK uniform or sailor suit, bright blue sky background, cherry blossoms, overexposed film photography look, youthful and energetic" },
  { id: 70, category: "Fashion", name: "牛仔风格", promptSuffix: "Denim fashion editorial, denim jacket and jeans, cool blue tones, casual street style, textured fabric detail, confident pose, modern Americana" },
  { id: 71, category: "Life", name: "生日少女风格", promptSuffix: "Birthday girl portrait, wearing a princess tiara, holding a cake with candles, balloons and party decor in background, sparkles, celebratory happy vibe" },
  { id: 72, category: "Fashion", name: "酷飒斩女风格", promptSuffix: "Cool girl crush style, sharp eyeliner, leather jacket, confident smirk, dynamic angle, k-pop idol stage presence, fierce and empowering" },
  { id: 73, category: "Wedding", name: "婚纱写真", promptSuffix: "Bridal portrait, white wedding dress with long veil, holding a bouquet of white roses, soft romantic lighting, dreamy garden or chapel background, elegant and ethereal" },
  { id: 74, category: "Dark", name: "暗黑写真", promptSuffix: "Gothic portrait, black lace dress, pale skin, dark red lips, victorian gothic aesthetic, mysterious castle background, moody atmosphere, cinematic lighting" },
  { id: 75, category: "Fashion", name: "辣妹风格", promptSuffix: "Y2K hot girl style, crop top, mini skirt, vibrant colors, 2000s fashion trends, playful pose, retro digital camera aesthetic, confident and spicy" },
  { id: 76, category: "Retro", name: "经典赫本风格", promptSuffix: "Audrey Hepburn style, black and white photography, little black dress, pearl necklace, updo hairstyle, cat eye sunglasses, vintage Hollywood glamour, timeless elegance" },
  { id: 77, category: "Fashion", name: "肯豆风格", promptSuffix: "Off-duty supermodel look, minimalist high fashion, sunglasses, slicked back hair, paparazzi style street photography, neutral tones, chic and modern city vibe" },

  // New Styles Batch 5 (New Year)
  { id: 78, category: "Holiday", name: "元旦新年风格", promptSuffix: "New Year's Day celebration portrait, festive confetti, holding sparklers, glamorous party outfit, happy hopeful expression, bokeh city lights background, 2025 vibes, modern and chic" },
  { id: 79, category: "Holiday", name: "中式农历新年", promptSuffix: "Chinese Lunar New Year Spring Festival portrait, wearing red festive clothing or modern tang suit, holding red lantern or red envelope, red background with gold paper cutouts, prosperous and joyful atmosphere, soft lighting" },

  // New Styles Batch 6 (Ethnic Minorities & Traditional)
  { id: 80, category: "Cultural", name: "藏族卓玛风格", promptSuffix: "Tibetan Zhuoma portrait, traditional Tibetan robe with colorful stripes, braided hair with turquoise and coral jewelry, plateau grassland background with prayer flags, sun-kissed cheeks, holy and pure" },
  { id: 81, category: "Cultural", name: "苗族银饰盛装", promptSuffix: "Grand Miao ethnic style, heavy intricate silver headdress (horns) and necklace, dark embroidered clothing with vibrant patterns, mystical mountain village background, heritage and ceremonial atmosphere" },
  { id: 82, category: "Cultural", name: "西域公主风格", promptSuffix: "Western Region Princess (Dunhuang style), exotic veil, golden accessories, flying ribbons (Feitian), desert dunes background, camel bells, mysterious and enchanting, Silk Road aesthetic" },
  { id: 83, category: "Cultural", name: "红色彝族风情", promptSuffix: "Red Yi ethnic style, vibrant red traditional clothing with black accents, flame patterns, intricate silver jewelry, celebration fire festival background, passionate and bold" },
  { id: 84, category: "Cultural", name: "蓝色彝族风情", promptSuffix: "Blue Yi ethnic style, deep blue and cyan traditional attire, distinct headwrap, silver ornaments, cool tone mountain background, mysterious and elegant, cold beauty" },
  { id: 85, category: "Art", name: "水墨国风", promptSuffix: "Chinese Ink Wash painting style, black and white watercolor background, calligraphy elements, traditional makeup, ethereal and poetic, like a character walking out of a scroll" },
  { id: 86, category: "Cultural", name: "哈尼甜心风格", promptSuffix: "Hani ethnic style, adorable and sweet, decorated headdress with beads and coins, colorful layers, terraced rice fields background, soft sunlight, lively and youthful" },
  { id: 87, category: "Cultural", name: "朝鲜公主风格", promptSuffix: "Traditional Joseon Dynasty princess, Hanbok with vibrant chima and jeogori, braided hair with daenggi ribbon, palace garden background, elegant and noble, historical drama vibe" },
  { id: 88, category: "Cultural", name: "傣族孔雀风格", promptSuffix: "Dai ethnic style, tight-fitting peacock dress showing curves, tropical rainforest background, frangipani flowers, wet look or water splashing festival vibe, exotic and graceful" },
  { id: 89, category: "Cultural", name: "壮族歌仙风格", promptSuffix: "Zhuang ethnic style, traditional blue and black clothing with intricate brocade, holding an embroidered ball, Guilin karst mountains background, folk song festival atmosphere" },
  { id: 90, category: "Cultural", name: "满族格格风格", promptSuffix: "Manchu noble lady (Gege), large floral headdress, ornate qipao/robe, silk scarf, Forbidden City red wall background, classical elegance, Qing dynasty court style" },
  { id: 91, category: "Cultural", name: "蒙古族草原风格", promptSuffix: "Mongolian princess, fur-trimmed hat, ornate robe (del), vast grassland background, yurt in distance, wind in hair, heroic and free-spirited" },
  { id: 92, category: "Cultural", name: "侗族大歌风格", promptSuffix: "Dong ethnic style, indigo dyed clothing, silver neck rings and headdress, Drum Tower architecture background, wooden bridge, cultural and artistic" }
];