import { PhotoStyle } from './types';

export const PHOTO_STYLES: PhotoStyle[] = [
  // 1-20 Original
  { id: 1, category: "Classic", name: "法式慵懒写真", promptSuffix: "French lazy style portrait, soft natural lighting, effortless chic, romantic atmosphere" },
  { id: 2, category: "Urban", name: "都市酷感机能风", promptSuffix: "Urban techwear style, cool vibes, street fashion, neon city background, futuristic functional clothing" },
  { id: 3, category: "Sweet", name: "少女梦幻写真", promptSuffix: "Dreamy teenage style, soft pastel colors, ethereal lighting, fairytale atmosphere, sparkles" },
  { id: 4, category: "Retro", name: "复古港风胶片", promptSuffix: "Hong Kong retro film style, 90s aesthetic, cinematic grain, moody lighting, nostalgic red and green tones" },
  { id: 5, category: "Minimal", name: "高级极简风", promptSuffix: "High-end minimalist style, clean background, neutral colors, fashion magazine editorial look" },
  { id: 6, category: "Business", name: "商务气场大片", promptSuffix: "Business professional power portrait, sharp suit, confident pose, modern office or studio background" },
  { id: 7, category: "Outdoor", name: "户外大景人像", promptSuffix: "Outdoor landscape portrait, epic scenery, wide angle, natural light, harmonious composition with nature" },
  { id: 8, category: "Mood", name: "雨夜情绪写真", promptSuffix: "Rainy night mood, cinematic lighting, wet streets, reflection, umbrella, melancholic atmosphere" },
  { id: 9, category: "Sci-Fi", name: "未来赛博风", promptSuffix: "Cyberpunk futuristic style, neon lights, glitch effects, high-tech accessories, night city" },
  { id: 10, category: "Life", name: "生活纪实风", promptSuffix: "Documentary lifestyle, candid moment, authentic, messy hair, cozy home or street setting" },
  { id: 11, category: "Art", name: "暗黑艺术风", promptSuffix: "Dark art aesthetic, gothic elements, dramatic shadows, mysterious, high contrast, moody" },
  { id: 12, category: "Sweet", name: "公主系甜美写真", promptSuffix: "Princess style, sweet and elegant, tiara, ballgown elements, soft pink and white tones, castle vibe" },
  { id: 13, category: "Sport", name: "运动元气系", promptSuffix: "Energetic sports style, sportswear, gym or track background, sweat, dynamic pose, bright daylight" },
  { id: 14, category: "Nature", name: "温室花房写真", promptSuffix: "Greenhouse conservatory, surrounded by flowers and plants, soft diffused sunlight, botanical aesthetic" },
  { id: 15, category: "Travel", name: "旅行度假风", promptSuffix: "Travel vacation style, tropical or landmark background, sunglasses, summer outfit, relaxed vibe" },
  { id: 16, category: "Japanese", name: "和风日系清冷", promptSuffix: "Japanese cool tone portrait, minimal, clean, soft blue tints, serene expression, film photography look" },
  { id: 17, category: "Lighting", name: "黄昏逆光写真", promptSuffix: "Golden hour backlight, silhouette, lens flare, warm orange tones, romantic and nostalgic" },
  { id: 18, category: "Cultural", name: "中式古典人像", promptSuffix: "Traditional Chinese classical portrait, hanfu elements, oriental aesthetics, elegant, ink painting vibe" },
  { id: 19, category: "Fashion", name: "城市摩登封面风", promptSuffix: "Modern city magazine cover, vogue style, bold makeup, statement fashion, skyscrapers in background" },
  { id: 20, category: "Creative", name: "情绪室内黑光", promptSuffix: "Indoor black light photography, UV reactive makeup, glowing neon paint, dark room, artistic experimentation" },

  // 21-50 Extended
  { id: 21, category: "Summer", name: "加州阳光海滩风", promptSuffix: "California sunshine, beach vibes, bright blue sky, palm trees, warm saturation, film kodak look" },
  { id: 22, category: "Minimal", name: "北欧清冷人像", promptSuffix: "Nordic minimal cold tone, white snow or grey concrete, clean lines, desaturated colors, winter vibes" },
  { id: 23, category: "Youth", name: "校园青春系", promptSuffix: "Campus youth, school uniform or casual hoodie, library or playground, fresh face, nostalgic school days" },
  { id: 24, category: "Sport", name: "都市夜跑运动风", promptSuffix: "Urban night runner, activewear, motion blur background, city street lights, sweat, intense focus" },
  { id: 25, category: "Art", name: "复古油画感人像", promptSuffix: "Oil painting style portrait, textured brushstrokes, classical lighting, museum quality, rich colors" },
  { id: 26, category: "Creative", name: "漫画分镜风", promptSuffix: "Manga storyboarding style, black and white ink, speech bubbles, dramatic angles, comic book aesthetic" },
  { id: 27, category: "Sci-Fi", name: "科幻光束摄影", promptSuffix: "Sci-fi light beam, laser lights, geometric shadows, futuristic studio, glowing lines" },
  { id: 28, category: "Retro", name: "蒸汽波色彩系", promptSuffix: "Vaporwave aesthetic, purple and teal gradient, retro 80s computer graphics, marble statues, glitch art" },
  { id: 29, category: "Art", name: "梦境反射水面", promptSuffix: "Dream reflection, water surface ripples, surreal composition, double exposure, mirrored world" },
  { id: 30, category: "Travel", name: "荒野公路风", promptSuffix: "Road trip wanderer, desert highway, vintage car, dusty boots, americana vibe, freedom" },
  { id: 31, category: "Vintage", name: "绅士/淑女复古肖像", promptSuffix: "Vintage gentleman/lady portrait, 1920s Gatsby style, tuxedo or flapper dress, sepia tone, elegant poise" },
  { id: 32, category: "Fantasy", name: "森林精灵系", promptSuffix: "Forest fairycore, magical woods, glowing fireflies, fantasy costume, mystical atmosphere" },
  { id: 33, category: "Mood", name: "极夜蓝调人像", promptSuffix: "Blue hour arctic mood, deep blue twilight, cold atmosphere, solitude, minimal light source" },
  { id: 34, category: "Life", name: "复古胶片家居感", promptSuffix: "Retro home film, cozy interior, warm tungsten light, grainy film texture, intimate and relaxed" },
  { id: 35, category: "Abstract", name: "超现实扭曲空间", promptSuffix: "Surreal distortion, dali-esque melting background, fish-eye lens, dream logic, strange perspective" },
  { id: 36, category: "Creative", name: "霓虹舞台人像", promptSuffix: "Neon stage portrait, spotlight, stage smoke, performance vibe, vibrant colors, pop star energy" },
  { id: 37, category: "Life", name: "咖啡馆文艺系", promptSuffix: "Cafe indie mood, looking through window, coffee cup, warm cozy tones, intellectual vibe, soft focus" },
  { id: 38, category: "Summer", name: "夏日泳池光影", promptSuffix: "Poolside summer glow, shimmering water caustics, bright sunlight, blue tiles, wet hair, refreshing" },
  { id: 39, category: "Street", name: "街头涂鸦色彩系", promptSuffix: "Graffiti pop color, urban wall art background, bold streetwear, vibrant saturation, hip hop culture" },
  { id: 40, category: "Industrial", name: "工业硬核风", promptSuffix: "Industrial metal aesthetic, abandoned factory, steel structures, rusty textures, cold rough lighting" },
  { id: 41, category: "Western", name: "美式牛仔西部风", promptSuffix: "Western cowboy/cowgirl, denim and leather, horse ranch background, sunset, rugged charm" },
  { id: 42, category: "Party", name: "夜店闪光捕捉", promptSuffix: "Flash photography party, direct flash, high contrast, club background, energetic, candid snapshot" },
  { id: 43, category: "Grunge", name: "脏乱美颓废风", promptSuffix: "Messy grunge portrait, torn clothes, smudged makeup, raw texture, rebellious attitude, 90s rock" },
  { id: 44, category: "Life", name: "温柔居家光", promptSuffix: "Morning soft light indoor, bed sheets, waking up, pure white sunlight, gentle and intimate" },
  { id: 45, category: "Costume", name: "万圣节角色扮演", promptSuffix: "Halloween cosplay portrait, dramatic costume, spooky makeup, theatrical lighting, character acting" },
  { id: 46, category: "Travel", name: "海岛随拍度假风", promptSuffix: "Island casual portrait, breeze in hair, ocean background, linen clothes, effortless vacation look" },
  { id: 47, category: "Art", name: "极具色块构成", promptSuffix: "Color-block avant-garde, solid geometric background colors, high fashion pose, abstract composition" },
  { id: 48, category: "Mood", name: "暗室红光摄影", promptSuffix: "Darkroom red light, safe light aesthetic, developing photos, monochromatic red, intense mood" },
  { id: 49, category: "Sci-Fi", name: "科技反射玻璃风", promptSuffix: "Tech glass reflection, looking through glass, digital overlays, prism effects, modern office futuristic" },
  { id: 50, category: "Silhouette", name: "星空下剪影", promptSuffix: "Silhouette under the stars, milky way background, starry night, mysterious outline, cosmic scale" },

  // New Holiday Styles
  { id: 51, category: "Holiday", name: "圣诞节日写真", promptSuffix: "Christmas holiday portrait, festive red and green, bokeh lights, snow, cozy winter vibe, Santa hat optional" },
  { id: 52, category: "Holiday", name: "复活节梦幻风", promptSuffix: "Easter holiday portrait, pastel colors, spring flowers, bunny ears element, soft dreamy lighting, wonderland" },
  { id: 53, category: "Holiday", name: "亡灵节暗黑风", promptSuffix: "Day of the Dead Dia de los Muertos, sugar skull makeup art, marigold flowers, vibrant colors, dark mysterious atmosphere" },
  
  // New Chinese Cultural Styles
  { id: 54, category: "Cultural", name: "中式汉服风格", promptSuffix: "Traditional Chinese Hanfu portrait, flowing silk robes, wide sleeves, intricate embroidery, elegant hairstyle with hairpins, ancient garden background, ethereal atmosphere" },
  { id: 55, category: "Cultural", name: "中式明朝服饰", promptSuffix: "Chinese Ming Dynasty portrait, mamianqun horse face skirt, cross-collar robe, gold jewelry, dignified pose, classical Chinese architecture background, rich colors" },
  { id: 56, category: "Cultural", name: "中式清朝服饰", promptSuffix: "Chinese Qing Dynasty portrait, traditional Manchurian dress, qipao, floral headdress (dianzi), delicate embroidery, palace garden background, noble elegance" },
  { id: 57, category: "Cultural", name: "苗族服饰风格", promptSuffix: "Miao ethnic minority portrait, elaborate silver headdress and jewelry, colorful embroidered traditional clothing, festival atmosphere, vibrant patterns, cultural heritage" },
  { id: 58, category: "Cultural", name: "彝族服饰风格", promptSuffix: "Yi ethnic minority portrait, traditional black and red clothing with yellow patterns, large fringed headwear, silver ornaments, mountainous landscape background, bold and spirited" }
];